from __future__ import annotations
from typing import Protocol
from models.color import Color

class IPhysicalStrip(Protocol):
    """Hardware abstraction: minimal interface for any LED strip."""
    @property
    def led_count(self) -> int: ...
    def set_pixel(self, index: int, color: Color) -> None: ...
    def show(self) -> None: ...
    def clear(self) -> None: ...

